repos:

- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
    - id: black

- repo: https://github.com/timothycrosley/isort
  rev: 5.10.1
  hooks:
  - id: isort

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.4.0'
  hooks:
    - id: check-builtin-literals
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-toml
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: forbid-new-submodules
    - id: trailing-whitespace

- repo: local
  hooks:
  - id: sort-json
    name: Sort theme.json
    language: python
    pass_filenames: false
    types: []
    always_run: true
    entry: python tools/sort-json.py
