name: CI

on:
  pull_request:
  push:
    branches: [master]
  schedule:
    - cron: 0 0 * * MON # Run every Monday at 00:00 UTC

env:
  COLUMNS: 120

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uvx pre-commit run --all-files --show-diff-on-failure

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uvx nox --default-venv-backend uv -s publish

      # Publish!
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' || github.event_name == 'schedule'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public/

      # Upload for introspection, useful for pull requests and debugging
      - uses: actions/upload-artifact@v4
        with:
          name: generated-site
          path: public/
