name: CI

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches: [master]
  schedule:
    - cron: 0 0 * * MON # Run every Monday at 00:00 UTC

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@v7
      - run: uvx prek run --all-files --show-diff-on-failure

  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: write # Pushing to `gh-pages` requires write permission

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@v7
      - run: uvx nox --default-venv-backend uv -s publish

      # Publish!
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' || github.event_name == 'schedule'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public/

      # Upload for introspection, useful for pull requests and debugging
      - uses: actions/upload-artifact@v4
        with:
          name: generated-site
          path: public/
